"""add aggregates table

Revision ID: 50a37bce1d12
Revises: f22717a1db4d
Create Date: 2025-12-11 10:19:09.531272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50a37bce1d12'
down_revision: Union[str, None] = 'f22717a1db4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('interval_start', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('interval_end', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'metric_name', 'interval_start', name='uq_client_metric_interval')
    )
    op.create_index('idx_client_metric_time', 'aggregates', ['client_id', 'metric_name', 'interval_start'], unique=False)
    op.create_index(op.f('ix_aggregates_client_id'), 'aggregates', ['client_id'], unique=False)
    op.create_index(op.f('ix_aggregates_interval_end'), 'aggregates', ['interval_end'], unique=False)
    op.create_index(op.f('ix_aggregates_interval_start'), 'aggregates', ['interval_start'], unique=False)
    op.create_index(op.f('ix_aggregates_metric_name'), 'aggregates', ['metric_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aggregates_metric_name'), table_name='aggregates')
    op.drop_index(op.f('ix_aggregates_interval_start'), table_name='aggregates')
    op.drop_index(op.f('ix_aggregates_interval_end'), table_name='aggregates')
    op.drop_index(op.f('ix_aggregates_client_id'), table_name='aggregates')
    op.drop_index('idx_client_metric_time', table_name='aggregates')
    op.drop_table('aggregates')
    # ### end Alembic commands ###
