"""add alerts and alert_history tables

Revision ID: bc45ac0e7528
Revises: 50a37bce1d12
Create Date: 2025-12-12 18:38:03.132594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc45ac0e7528'
down_revision: Union[str, None] = '50a37bce1d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('triggered_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_time', 'alert_history', ['alert_id', 'triggered_at'], unique=False)
    op.create_index('idx_client_time', 'alert_history', ['client_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_history_client_id'), 'alert_history', ['client_id'], unique=False)
    op.create_index(op.f('ix_alert_history_triggered_at'), 'alert_history', ['triggered_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('notification_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_client_enabled', 'alerts', ['client_id', 'enabled'], unique=False)
    op.create_index(op.f('ix_alerts_client_id'), 'alerts', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_client_id'), table_name='alerts')
    op.drop_index('idx_client_enabled', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_history_triggered_at'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_client_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_index('idx_client_time', table_name='alert_history')
    op.drop_index('idx_alert_time', table_name='alert_history')
    op.drop_table('alert_history')
    # ### end Alembic commands ###
